# Generated by Django 2.2.3 on 2019-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='location',
        ),
        migrations.AddField(
            model_name='book',
            name='file_name',
            field=models.CharField(default='something', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='file_url',
            field=models.CharField(default='www.dfgdfg.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pub_name',
            field=models.CharField(default='alex', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='uuid',
            field=models.CharField(default='fdsdfds34s', max_length=30),
            preserve_default=False,
        ),
    ]
